version: "3.7"
services:
  users-api:
    build:
      context: users-api
      dockerfile: Dockerfile
    environment:
      DB_USERNAME: "postgres"
      DB_PASSWORD: ${DB_PASSWORD:-dMVZFeBWLOzYRV71} #It is strongly recommended to provide DB_PASSWORD in the environment rather than use this default.
      POSTGRES_DB: "postgres"
      DB_HOST: "users-db"
      LOAD_DATA: "True"
    ports:
      - 8080:8080
    depends_on:
      - users-db
    volumes:
      - ./users-api:/app

  users-ui:
    build:
      context: users-ui
      dockerfile: Dockerfile
    ports:
      - 5000:80
    depends_on:
      - users-api
    volumes:
      - ./users-ui:/app

  users-db:
    build:
      context: db
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: ${DB_PASSWORD:-dMVZFeBWLOzYRV71}
      POSTGRES_DB: "postgres"
      DB_BACKUP_URL: "https://storage.googleapis.com/anonymize-db-backups/us-west1/backup.sql"
      RESTORE_FROM_BACKUP: "False"
    ports:
      - 5432:5432
    volumes:
      - ./db:/db
